#!/bin/bash
source /opt/intel/composerxe/bin/compilervars.sh intel64
echo MKLROOT=$MKLROOT
echo INTEL_LICENSE_FILE=$INTEL_LICENSE_FILE
echo IPPROOT=$IPPROOT
echo GDBSERVER_MIC=$GDBSERVER_MIC
echo LIBRARY_PATH=$LIBRARY_PATH
echo MIC_LD_LIBRARY_PATH=$MIC_LD_LIBRARY_PATH
echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
echo MIC_LIBRARY_PATH=$MIC_LIBRARY_PATH
echo CPATH=$CPATH
echo NLSPATH=$NLSPATH
echo PATH=$PATH
echo TBBROOT=$TBBROOT
echo IDB_HOME=$IDB_HOME
echo GDB_CROSS=$GDB_CROSS
echo MPM_LAUNCHER=$MPM_LAUNCHER
echo INCLUDE=$INCLUDE
