#!/usr/bin/env python
###############################################################################
# Copyright 2016,2017 Cray Inc. All Rights Reserved.
#
# REL_check - a wrapper script that can be used to quickly run the REL_check using WTS 
#
# author: Pete Halseth
#
# Usage:
# -------
# ./REL_check -h 
# 
################################################################################
##@package workload
# a basic script to check status of the WTS REL test 
import xtsystest 

if __name__ == '__main__':
    xtsystest.process_commandline_options()
    if not xtsystest.MODULE_CONFIG['user_options']['input_file_path']:
        xtsystest.MODULE_CONFIG['user_options']['input_file_path'] = xtsystest.FULL_PATH_TO_SCRIPT_DIR + "/runrel_knl.ini"
    xtsystest.MODULE_CONFIG['user_options']['run_report'] = 1 
    xtsystest.main(xtsystest.MODULE_CONFIG['user_options']) 
