#!/bin/bash

unset -x

if [[ $# -eq 0 ]] ; then
    echo 'USAGE: clean_auc_link_error <dead_link>'
    exit 0
fi

echo $1

if ! $(dcnu -i $1 | grep -q blue)
then
    echo 'script works only with AUC ( blue ) links'
fi

xtwarmswap --remove-cable $(rtr --connector-link-map=$1 | awk '{ print $2 }')

read -p "link removed, do you want to add it back? " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

xtwarmswap --add-cable $(rtr --connector-link-map=$1 | awk '{ print $2 }') --linktune
