#!/usr/bin/env python
###############################################################################
# Copyright 2016 Cray Inc. All Rights Reserved.
#
# RUNmem - a wrapper script that can be used to quickly run the RUNmem test list using WTS 
#
# author: Pete Halseth
#
# Usage:
# -------
# ./RUNmem 
# 
################################################################################
##@package workload
# a basic script to run the WTS RUNmem test 
import xtsystest 

if __name__ == '__main__':
    xtsystest.process_commandline_options()
    if not xtsystest.MODULE_CONFIG['user_options']['input_file_path']:
        xtsystest.MODULE_CONFIG['user_options']['input_file_path'] = xtsystest.FULL_PATH_TO_SCRIPT_DIR + "/runmem_knl.ini"
    xtsystest.main(xtsystest.MODULE_CONFIG['user_options'])
