#!/usr/bin/env python
###############################################################################
# Copyright 2016,2017 Cray Inc. All Rights Reserved.
#
# RUNmem_check - a wrapper script that can be used to quickly scan the RUNmem logs 
#
# author: Pete Halseth
#
# Usage:
# -------
# ./RUNmem_check -h  
# 
################################################################################
##@package workload
# a basic script to check status of the WTS RUNmem test 
import xtsystest 

if __name__ == '__main__':
    xtsystest.process_commandline_options()
    if not xtsystest.MODULE_CONFIG['user_options']['input_file_path']:
        xtsystest.MODULE_CONFIG['user_options']['input_file_path'] = xtsystest.FULL_PATH_TO_SCRIPT_DIR + "/runmem_knl.ini"
    xtsystest.MODULE_CONFIG['user_options']['run_report'] = 1 
    xtsystest.main(xtsystest.MODULE_CONFIG['user_options']) 
