#!/usr/bin/env python
###############################################################################
# Copyright 2017 Cray Inc. All Rights Reserved.
#
# RUNnls - a wrapper script that can be used to quickly check the RUNnls test using WTS 
#
# author: Dean Balts
#
# Usage:
# -------
# ./RUNnls_check -h
# 
################################################################################
##@package workload
# a basic script to check status of the WTS RUNnls test 
import xtsystest

if __name__ == '__main__':
    xtsystest.process_commandline_options()
    if not xtsystest.MODULE_CONFIG['user_options']['input_file_path']:
        xtsystest.MODULE_CONFIG['user_options']['input_file_path'] = xtsystest.FULL_PATH_TO_SCRIPT_DIR + "/runnls.ini"
    xtsystest.MODULE_CONFIG['user_options']['run_report'] = 1
    xtsystest.main(xtsystest.MODULE_CONFIG['user_options'])

