#!/usr/bin/env python
###############################################################################
# Copyright 2016 Cray Inc. All Rights Reserved.
#
# RUNlong_check - a wrapper script that can quickly check the results
# of the RUNlong test list using WTS 
#
# author: Pete Halseth
#
# Usage:
# -------
# ./RUNlong_check -h
# 
################################################################################
##@package workload
# a basic script to check status of the WTS RUNlong test 
import xtsystest 

if __name__ == '__main__':
    xtsystest.process_commandline_options()
    if not xtsystest.MODULE_CONFIG['user_options']['input_file_path']:
        xtsystest.MODULE_CONFIG['user_options']['input_file_path'] = xtsystest.FULL_PATH_TO_SCRIPT_DIR + "/runlong_knl.ini"
    xtsystest.MODULE_CONFIG['user_options']['run_report'] = 1 
    xtsystest.main(xtsystest.MODULE_CONFIG['user_options']) 
